'use strict';

const { resolveSkitHome, ensureDirs, loadConfig, saveConfig } = require('../index');
const { listSkills } = require('../core/manifest');
const { version } = require('../../package.json');
const format = require('../ui/format');

const TIPS = [
  // Informational
  'Run `skit discover` to find untracked skills in your agent\'s folder',
  '`skit doctor` catches broken links before they ruin your day',
  '`skit sync` is your friend on a new machine',
  '`skit update` pulls the latest from all your skill sources at once',
  '`skit clone <user>` copies another person\'s entire skill setup',
  'Use `--all` with `skit install` to skip the picker and grab everything',
  '`skit config set agent cursor` switches your active agent',
  '`skit profile export` creates a shareable snapshot of your full setup',
  'Skills with a `SKILL.md` show up better in the registry — and in doctor',
  'Run `skit discover` after switching agents — each has its own skill folder',
  '`skit incognito on` gives this project a clean slate — global skills stay home',
  '`skit import <gist-url>` pulls a skill directly from a GitHub Gist',
  'Keep your skills folder lean — unused skills waste your agent\'s context',
  'A good skill does one thing well. A great skill documents it in SKILL.md.',
  'Tip: commit your skit profile to git. Future you will thank present you.',
  // Witty / smile-inducing
  'Your agent is only as good as its skills. No pressure.',
  'Installing skills won\'t make your agent sentient. Probably.',
  'The difference between a great dev and an okay dev: about 47 well-placed skills',
  'Skills: because prompt engineering has diminishing returns after 3am',
  'Fun fact: this TUI was built with the help of skills. Meta.',
  'Somewhere, an AI is reading this tip and feeling seen.',
  'The best skill is the one you wrote yourself and then forgot about',
  'If in doubt, `skit doctor`. If still in doubt, step outside.',
  'Your skills outlive your chat history. Choose wisely.',
  'A tidy skills folder is a tidy mind. (We read that somewhere.)',
  'You\'re one `skit install` away from being 10x more productive. Or 9x. We\'re not monsters.',
  'Claude doesn\'t sleep. Your skills folder shouldn\'t be a mess either.',
  'This is not a prompt injection. This is a tip. There is a difference. (Allegedly.)',
  'Not all heroes wear capes. Some of them write SKILL.md files.',
  'Your future self is watching. Make the good choices.',
  '"It works on my machine" — famous last words before `skit sync`',
  'The vibes are immaculate. The skills should be too.',
  'skit: built different. (We\'re not sure how, but we\'re committing to it.)',
  // AI culture easter eggs
  'GPT can\'t do this. (We\'re biased. But still.)',
  'This tip was not generated by o3. Probably.',
  'RAG is great. Skills don\'t need a vector database.',
  'Context windows are finite. Good skills make every token count.',
  'In the time it took to read this, Claude processed a lot of tokens. Hi Claude.',
  'Agents are only as smart as their tools. You\'re the tool curator now.',
  'MCP servers are great. Skills are portable. Why not both?',
  'Vibe coding is fine. Vibe skill management is not.',
  'The model is not the moat. The skills are.',
  'Skills age better than model weights.',
  'Remember when everyone was building chatbots? Now we build agents. Wild.',
  'Windsurf, Cursor, Claude Code — skit works with all of them. We contain multitudes.',
  'Your agent called. It wants more skills.',
  'Hot take: good skills > fine-tuning. (Debatable. We stand by it.)',
  'Some people meditate. Others run `skit doctor` at 2am. You know who you are.',
  'Building AI products in 2026: 40% prompting, 30% skills, 30% explaining it to stakeholders.',
  'No, this tool doesn\'t use RAG. It just has good taste.',
];

function printHeader(skillCount, tip) {
  const art = [
    ' ___  _    _ _   ',
    '/ __|| |  (_) |_ ',
    '\\__ \\| |/ /| || __|',
    '|   /|  < | || |_ ',
    ' \\_/ |_|\\_\\|_| \\__|',
  ];
  console.log('');
  // Print ASCII art with version on last line
  for (let i = 0; i < art.length; i++) {
    if (i === art.length - 1) {
      console.log(format.info(art[i]) + format.dim(`  v${version}`));
    } else {
      console.log(format.info(art[i]));
    }
  }
  console.log('');
  const skillLabel = `${skillCount} skill${skillCount === 1 ? '' : 's'} installed`;
  console.log(format.dim(`  ${skillLabel}`));
  console.log(format.dim(`  ${tip}`));
  console.log('');
}

async function tui(options = {}) {
  const skitHome = options.skitHome || resolveSkitHome();
  ensureDirs(skitHome);

  const config = loadConfig(skitHome);
  const skills = listSkills(skitHome);
  let skillCount = Object.keys(skills).length;

  const pickAction = options._pickAction || _defaultPickAction;
  const browseScreen = options._browse || require('./tui/browse').browseRegistry;
  const mySkillsScreen = options._mySkills || require('./tui/my-skills').mySkills;
  const doctor = options._doctor || require('./doctor').doctor;
  const update = options._update || require('./update').update;
  const sync = options._sync || require('./sync').sync;
  const inquirer = options._inquirer || require('inquirer');

  const tip = TIPS[Math.floor(Math.random() * TIPS.length)];
  printHeader(skillCount, tip);

  // First-run onboarding
  if (!config.discovered) {
    const discoverFn = options._discover || require('./discover').discover;
    await runFirstTimeOnboard({ skitHome, config, discoverFn, options });
    // Reload skill count after potential discovery
    const updatedSkills = listSkills(skitHome);
    skillCount = Object.keys(updatedSkills).length;
  }

  const choice = await pickAction('What would you like to do?', [
    { name: 'Browse registry', value: 'browse' },
    { name: 'My skills',       value: 'my-skills' },
    { name: 'Discover skills', value: 'discover' },
    { name: 'Update / sync',   value: 'update-sync' },
    { name: 'Health check',    value: 'health-check' },
    { name: 'Exit',            value: 'exit' },
  ]);

  switch (choice) {
    case 'browse':
      await browseScreen({ skitHome });
      break;
    case 'my-skills':
      await mySkillsScreen({ skitHome });
      break;
    case 'discover':
      await (options._discover || require('./discover').discover)({ skitHome });
      break;
    case 'update-sync':
      await update(undefined, { skitHome });
      await sync({ skitHome });
      break;
    case 'health-check':
      await doctor({ skitHome });
      break;
    case 'exit':
    default:
      break;
  }
}

async function runFirstTimeOnboard({ skitHome, config, discoverFn, options }) {
  const inq = options._inquirer || require('inquirer');

  console.log(format.info('  ✦ Welcome! Looks like this is your first run.'));
  console.log(format.dim('    skit can scan your agent\'s skills folder and take over managing it.'));
  console.log(format.dim('    Nothing will be moved, deleted, or changed — just catalogued.'));
  console.log('');

  let doScan;
  try {
    const answer = await inq.prompt([{
      type: 'confirm',
      name: 'scan',
      message: 'Scan for existing skills now?',
      default: true,
    }]);
    doScan = answer.scan;
  } catch {
    doScan = false;
  }

  if (doScan) {
    await discoverFn({ skitHome, agentSkillDir: options.agentSkillDir, _inquirer: options._inquirer });
  }

  // Mark as onboarded regardless of choice — never ask again
  config.discovered = true;
  saveConfig(skitHome, config);
  console.log('');
}

async function _defaultPickAction(message, choices) {
  const { pickAction } = require('../ui/picker');
  return pickAction(message, choices);
}

module.exports = { tui };
